module.exports = {
  SKILL_USED_BY_PROJECT: 'SKILL_USED_BY_PROJECT',
  PROJECT_APPLICATION_CREATED: 'PROJECT_APPLICATION_CREATED',
  PROJECT_APPLICATION_APPROVED: 'PROJECT_APPLICATION_APPROVED',
  PROJECT_APPLICATION_DECLINED: 'PROJECT_APPLICATION_DECLINED'
};
