module.exports = {
  FACEBOOK: 'FACEBOOK',
  GITHUB: 'GITHUB',
  LINKEDIN: 'LINKEDIN',
  TWITTER: 'TWITTER',
  MEETUP: 'MEETUP',
  DRIBBBLE: 'DRIBBBLE',
  PINTEREST: 'PINTEREST',
  BEHANCE: 'BEHANCE',
  YELP: 'YELP',
  GOODREADS: 'GOODREADS',
  INSTAGRAM: 'INSTAGRAM',
  WEBSITE: 'WEBSITE',
  MEDIUM: 'MEDIUM',
  BLOG: 'BLOG'
};
