module.exports = {
  ICON_FACEBOOK: 'ICON_FACEBOOK',
  ICON_GITHUB: 'ICON_GITHUB',
  ICON_LINKEDIN: 'ICON_LINKEDIN',
  ICON_TWITTER: 'ICON_TWITTER',
  ICON_MEETUP: 'ICON_MEETUP',
  ICON_DRIBBBLE: 'ICON_DRIBBBLE',
  ICON_BEHANCE: 'ICON_BEHANCE',
  ICON_YELP: 'ICON_YELP',
  ICON_GOODREADS: 'ICON_GOODREADS',
  ICON_INSTAGRAM: 'ICON_INSTAGRAM',
  ICON_WEBSITE: 'ICON_WEBSITE',
  ICON_MEDIUM: 'ICON_MEDIUM',
  ICON_BLOG: 'ICON_BLOG'
};
