module.exports = {
  PROFILE_PIC_USER: 'PROFILE_PIC_USER',
  PROFILE_PIC_PROJECT: 'PROFILE_PIC_PROJECT',
  PROFILE_PIC_ORGANIZATION: 'PROFILE_PIC_ORGANIZATION',
  BANNER_PIC_PROJECT: 'BANNER_PIC_PROJECT'
};
